#!/usr/bin/env bash

file=$1
w=$2
h=$3
x=$4
y=$5

filetype="$( file -Lb --mime-type "$file")"

case "$filetype" in
    image/*)
        kitty \
            +kitten icat \
            --silent \
            --stdin no \
            --transfer-mode file \
            --place "${w}x${h}@${x}x${y}" \
            "$file" \
            < /dev/null \
            > /dev/tty
        exit 1
        ;;
    text/*)
        bat \
            --style=numbers \
            --color=always \
            "$file"
        ;;
    *)
        echo "Preview unsupported:"
        file -b "$file"
        ;;
esac
