#!/usr/bin/env bash

f=$1
w=$2
h=$3
x=$4
y=$5

filetype="$( file -Lb --mime-type "${f}")"

bat_with_opts() {
    bat \
        --style=numbers \
        --color=always \
        --terminal-width="${w}" \
        "$@"
}

case "$filetype" in
    image/*)
        kitten icat \
            --stdin no \
            --transfer-mode memory \
            --place "${w}x${h}@${x}x${y}" \
            "${f}" \
            > /dev/tty
        exit 1
        ;;
    application/json)
        jq < "${f}" | bat_with_opts --language json
        ;;
    text/*)
        bat_with_opts "${f}"
        ;;
    *)
        echo "- Preview unsupported for mime-type: $filetype"
        echo "- Information (\`file -b\`):"
        file -b "${f}" | fmt -w "${w}"
        ;;
esac
