#!/usr/bin/env bash

file=$1
w=$2
h=$3
x=$4
y=$5

filetype="$( file -Lb --mime-type "$file")"

bat_with_opts() {
    bat \
        --style=numbers \
        --color=always \
        --terminal-width="${w}" \
        "$@"
}

case "$filetype" in
    image/*)
        kitten icat \
            --silent \
            --stdin no \
            --transfer-mode file \
            --place "${w}x${h}@${x}x${y}" \
            "$file" \
            < /dev/null \
            > /dev/tty
        exit 1
        ;;
    application/json)
        jq < "$file" | bat_with_opts --language json
        ;;
    text/*)
        bat_with_opts "$file"
        ;;
    *)
        echo "- Preview unsupported for mime-type: $filetype"
        echo "- Information (\`file -b\`):"
        file -b "$file" | fmt -w "${w}"
        ;;
esac
