#!/usr/bin/env bash

# Warn about nested instances
&[ $LF_LEVEL -eq 1 ] || lf -remote "send $id echoerr \"Warning: You're in a nested lf instance!\""

# Like bash's PS1
set promptfmt "
\033[1mlf> 
\033[92;1m%u
\033[0m@
\033[32;1m%h
\033[0m:
\033[94;1m%d
\033[0m\033[1m%f\033[0m
"

# Show (relative) line numbers
set number
set relativenumber

# Like Vim's scrolloff
set scrolloff 5

# Show hidden files (.foo_file)
set hidden

# Mappings
map V invert-below
map g/ cd /

# Write current directory to a file specified by the invoking shell
cmd quit-and-cd &{{
    pwd > $LF_CD_FILE
    lf -remote "send $id quit"
}}
map Q quit-and-cd
map
