# Colors
set-option -g default-terminal "tmux-256color"

# Escape key delay
set-option -sg escape-time 0

# Copy mode
set-option -g mouse on
setw -g mode-keys vi

# # Rebind prefix key
# unbind C-b
# set-option -g prefix C-M-w
# bind-key C-M-w send-prefix
# 
# # Vim-like pane splitting
# unbind '"'
# unbind %
# bind s split-window -v
# bind v split-window -h
# 
# # Vim-like pane navigation
# unbind Left
# unbind Down
# unbind Up
# unbind Right
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R
