#!/usr/bin/env bash

set -e

cp_old() {
    if [[ -z "$old_dir" ]]; then
        old_dir='old'
        local i=1
        while [[ -e "$old_dir$i" ]]; do
            (( i++ ))
        done
        old_dir+="$i"
        mkdir "$old_dir"
    fi

    cp "$1" "$old_dir"
}

while read name; do
    there="$HOME/${name:2}"
    [[ -h "$there" ]] && rm "$there"
    if [[ -e "$there" ]]; then
        cp_old "$there"
        rm "$there"
    fi
    
    there_dir="${there%/*}"
    [[ -d "$there_dir" ]] || mkdir -p "$there_dir"

    here="$PWD/${name:2}"
    ln -sf "$here" "$there_dir"
done <<< "$(find . -type f \
    \! -path './link' \
    \! -path './old*' \
    \! -path './.git*' \
)"
